language: php
php:
- 7.1
- 7.2
matrix:
  fast_finish: true
sudo: true
cache:
  directories:
  - vendor
before_install:
  - sudo pip install codecov
  - curl -O https://download.arangodb.com/arangodb32/xUbuntu_17.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb https://download.arangodb.com/arangodb32/xUbuntu_17.04/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install arangodb3=3.2.6
install:
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - bash run-tests.sh
after_success:
  - codecov
after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage/coverage.clover
notifications:
  email: false